#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ngraph
Version  : 0.22.0
Release  : 5
URL      : https://github.com/NervanaSystems/ngraph/archive/v0.22.0.tar.gz
Source0  : https://github.com/NervanaSystems/ngraph/archive/v0.22.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause MIT MPL-2.0-no-copyleft-exception NCSA OFL-1.1
Requires: ngraph-lib = %{version}-%{release}
Requires: ngraph-license = %{version}-%{release}
Requires: numpy
Requires: six
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : doxygen
BuildRequires : git
BuildRequires : numpy
BuildRequires : openmpi-dev
BuildRequires : protobuf-dev
BuildRequires : six
BuildRequires : zlib-dev
Patch1: 0001-ngraph-compile-for-DLDT-R2.patch

%description
![nGraph Compiler stack](doc/sphinx/source/graphics/ngraph_header.png)
[![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://github.com/NervanaSystems/ngraph/blob/master/LICENSE) [![Build Status][build-status-badge]][build-status]

%package dev
Summary: dev components for the ngraph package.
Group: Development
Requires: ngraph-lib = %{version}-%{release}
Provides: ngraph-devel = %{version}-%{release}
Requires: ngraph = %{version}-%{release}

%description dev
dev components for the ngraph package.


%package lib
Summary: lib components for the ngraph package.
Group: Libraries
Requires: ngraph-license = %{version}-%{release}

%description lib
lib components for the ngraph package.


%package license
Summary: license components for the ngraph package.
Group: Default

%description license
license components for the ngraph package.


%prep
%setup -q -n ngraph-0.22.0
cd %{_builddir}/ngraph-0.22.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588361715
pushd src
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DNGRAPH_LIB_VERSIONING_ENABLE=TRUE \
-DNGRAPH_STATIC_LIB_ENABLE=FALSE \
-DNGRAPH_API_VERSION=0.22
make  %{?_smp_mflags}  VERBOSE=1
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
export FFLAGS="$FFLAGS -march=haswell -m64"
export FCFLAGS="$FCFLAGS -march=haswell -m64"
%cmake .. -DNGRAPH_LIB_VERSIONING_ENABLE=TRUE \
-DNGRAPH_STATIC_LIB_ENABLE=FALSE \
-DNGRAPH_API_VERSION=0.22
make  %{?_smp_mflags}  VERBOSE=1
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export CFLAGS="$CFLAGS -march=skylake-avx512 -m64 "
export CXXFLAGS="$CXXFLAGS -march=skylake-avx512 -m64 "
export FFLAGS="$FFLAGS -march=skylake-avx512 -m64 "
export FCFLAGS="$FCFLAGS -march=skylake-avx512 -m64 "
%cmake .. -DNGRAPH_LIB_VERSIONING_ENABLE=TRUE \
-DNGRAPH_STATIC_LIB_ENABLE=FALSE \
-DNGRAPH_API_VERSION=0.22
make  %{?_smp_mflags}  VERBOSE=1
popd
popd

%install
export SOURCE_DATE_EPOCH=1588361715
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ngraph
cp %{_builddir}/ngraph-0.22.0/LICENSE %{buildroot}/usr/share/package-licenses/ngraph/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
cp %{_builddir}/ngraph-0.22.0/licenses/Apache-2.0-license.txt %{buildroot}/usr/share/package-licenses/ngraph/3fa2daf91c6f9dcf7c767a7b755fa36a23debc4f
cp %{_builddir}/ngraph-0.22.0/licenses/OFL-license.txt %{buildroot}/usr/share/package-licenses/ngraph/293bda57df5fd753d536918973e0cbdc7ad2a3f5
cp %{_builddir}/ngraph-0.22.0/licenses/caffe2-license.txt %{buildroot}/usr/share/package-licenses/ngraph/48a395f1045c617d1b407e8372bd77c8f71bf86c
cp %{_builddir}/ngraph-0.22.0/licenses/eigen-license.txt %{buildroot}/usr/share/package-licenses/ngraph/60e7040879300ea5e3cb2f6e4437b001ef85811b
cp %{_builddir}/ngraph-0.22.0/licenses/googletest-license.txt %{buildroot}/usr/share/package-licenses/ngraph/37571ac0358829b2175835de61c68818dd709239
cp %{_builddir}/ngraph-0.22.0/licenses/jquery-license.txt %{buildroot}/usr/share/package-licenses/ngraph/594e887872eacc74920a5eb310c1f9ee34dcf131
cp %{_builddir}/ngraph-0.22.0/licenses/json-license.txt %{buildroot}/usr/share/package-licenses/ngraph/f37bc6749b691bf29592797db379cf0e390bb8b7
cp %{_builddir}/ngraph-0.22.0/licenses/llvm-license.txt %{buildroot}/usr/share/package-licenses/ngraph/840cef56b46b261f9d3faba6e79f4da93126f63a
cp %{_builddir}/ngraph-0.22.0/licenses/mkl-dnn-license.txt %{buildroot}/usr/share/package-licenses/ngraph/385bdbc74ad1af072775c2366445b9a20b96f1d0
cp %{_builddir}/ngraph-0.22.0/licenses/mklml-license.txt %{buildroot}/usr/share/package-licenses/ngraph/8d9c29c48565d4d4283216c4c63e4fe31cc56257
cp %{_builddir}/ngraph-0.22.0/licenses/numpy-license.txt %{buildroot}/usr/share/package-licenses/ngraph/051b823186e06740361b3bd1ec3e1ba37b836f36
cp %{_builddir}/ngraph-0.22.0/licenses/pybind11-license.txt %{buildroot}/usr/share/package-licenses/ngraph/9e66a6e615665d81e0518564c4f93927a41a5d8c
cp %{_builddir}/ngraph-0.22.0/licenses/sphinx-license.txt %{buildroot}/usr/share/package-licenses/ngraph/62e83dae35534c2dd6abbefe96698b182a900c15
cp %{_builddir}/ngraph-0.22.0/licenses/sphinx_rtd_theme-license.txt %{buildroot}/usr/share/package-licenses/ngraph/ff83fbccde4452fe6eded294096f1f164c3519dd
cp %{_builddir}/ngraph-0.22.0/licenses/swagger-ui-license.txt %{buildroot}/usr/share/package-licenses/ngraph/b63a31e4a6af5b8d9432771d7e737b8cbd40315b
cp %{_builddir}/ngraph-0.22.0/licenses/tbb-license.txt %{buildroot}/usr/share/package-licenses/ngraph/7a511ea6464485d919713d82ca7a175e3be9b407
cp %{_builddir}/ngraph-0.22.0/licenses/tensorflow-license.txt %{buildroot}/usr/share/package-licenses/ngraph/02d5a8aa5c17fd84b6d53f0ce2820f7df439873c
pushd src
pushd clr-build-avx512
%make_install_avx512  || :
popd
pushd clr-build-avx2
%make_install_avx2  || :
popd
pushd clr-build
%make_install
popd
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ngraph/assertion.hpp
/usr/include/ngraph/autodiff/adjoints.hpp
/usr/include/ngraph/axis_set.hpp
/usr/include/ngraph/axis_vector.hpp
/usr/include/ngraph/builder/autobroadcast.hpp
/usr/include/ngraph/builder/make_constant.hpp
/usr/include/ngraph/builder/norm.hpp
/usr/include/ngraph/builder/numpy_transpose.hpp
/usr/include/ngraph/builder/quantization.hpp
/usr/include/ngraph/builder/quantization/quantized_linear_convolution.hpp
/usr/include/ngraph/builder/quantization/quantized_linear_matmul.hpp
/usr/include/ngraph/builder/quantization_util.hpp
/usr/include/ngraph/builder/reduce_ops.hpp
/usr/include/ngraph/builder/reshape.hpp
/usr/include/ngraph/builder/split.hpp
/usr/include/ngraph/builder/tensor_mask.hpp
/usr/include/ngraph/check.hpp
/usr/include/ngraph/code_writer.hpp
/usr/include/ngraph/codegen/codegen_visibility.h
/usr/include/ngraph/codegen/compiler.hpp
/usr/include/ngraph/codegen/execution_engine.hpp
/usr/include/ngraph/coordinate.hpp
/usr/include/ngraph/coordinate_diff.hpp
/usr/include/ngraph/coordinate_transform.hpp
/usr/include/ngraph/cpio.hpp
/usr/include/ngraph/deprecated.hpp
/usr/include/ngraph/descriptor/input.hpp
/usr/include/ngraph/descriptor/layout/dense_tensor_layout.hpp
/usr/include/ngraph/descriptor/layout/tensor_layout.hpp
/usr/include/ngraph/descriptor/output.hpp
/usr/include/ngraph/descriptor/tensor.hpp
/usr/include/ngraph/dimension.hpp
/usr/include/ngraph/distributed.hpp
/usr/include/ngraph/distributed/mlsl.hpp
/usr/include/ngraph/distributed/null.hpp
/usr/include/ngraph/distributed/open_mpi.hpp
/usr/include/ngraph/event_tracing.hpp
/usr/include/ngraph/except.hpp
/usr/include/ngraph/file_util.hpp
/usr/include/ngraph/frontend/onnx_import/core/attribute.hpp
/usr/include/ngraph/frontend/onnx_import/core/graph.hpp
/usr/include/ngraph/frontend/onnx_import/core/model.hpp
/usr/include/ngraph/frontend/onnx_import/core/node.hpp
/usr/include/ngraph/frontend/onnx_import/core/null_node.hpp
/usr/include/ngraph/frontend/onnx_import/core/operator_set.hpp
/usr/include/ngraph/frontend/onnx_import/core/tensor.hpp
/usr/include/ngraph/frontend/onnx_import/core/value_info.hpp
/usr/include/ngraph/frontend/onnx_import/core/weight.hpp
/usr/include/ngraph/frontend/onnx_import/exceptions.hpp
/usr/include/ngraph/frontend/onnx_import/onnx.hpp
/usr/include/ngraph/frontend/onnx_import/op/abs.hpp
/usr/include/ngraph/frontend/onnx_import/op/acos.hpp
/usr/include/ngraph/frontend/onnx_import/op/acosh.hpp
/usr/include/ngraph/frontend/onnx_import/op/add.hpp
/usr/include/ngraph/frontend/onnx_import/op/and.hpp
/usr/include/ngraph/frontend/onnx_import/op/argmax.hpp
/usr/include/ngraph/frontend/onnx_import/op/argmin.hpp
/usr/include/ngraph/frontend/onnx_import/op/asin.hpp
/usr/include/ngraph/frontend/onnx_import/op/asinh.hpp
/usr/include/ngraph/frontend/onnx_import/op/atan.hpp
/usr/include/ngraph/frontend/onnx_import/op/atanh.hpp
/usr/include/ngraph/frontend/onnx_import/op/average_pool.hpp
/usr/include/ngraph/frontend/onnx_import/op/batch_norm.hpp
/usr/include/ngraph/frontend/onnx_import/op/cast.hpp
/usr/include/ngraph/frontend/onnx_import/op/ceil.hpp
/usr/include/ngraph/frontend/onnx_import/op/clip.hpp
/usr/include/ngraph/frontend/onnx_import/op/concat.hpp
/usr/include/ngraph/frontend/onnx_import/op/constant.hpp
/usr/include/ngraph/frontend/onnx_import/op/conv.hpp
/usr/include/ngraph/frontend/onnx_import/op/conv_integer.hpp
/usr/include/ngraph/frontend/onnx_import/op/conv_transpose.hpp
/usr/include/ngraph/frontend/onnx_import/op/cos.hpp
/usr/include/ngraph/frontend/onnx_import/op/cosh.hpp
/usr/include/ngraph/frontend/onnx_import/op/depth_to_space.hpp
/usr/include/ngraph/frontend/onnx_import/op/dequantize_linear.hpp
/usr/include/ngraph/frontend/onnx_import/op/div.hpp
/usr/include/ngraph/frontend/onnx_import/op/dropout.hpp
/usr/include/ngraph/frontend/onnx_import/op/elu.hpp
/usr/include/ngraph/frontend/onnx_import/op/equal.hpp
/usr/include/ngraph/frontend/onnx_import/op/erf.hpp
/usr/include/ngraph/frontend/onnx_import/op/exp.hpp
/usr/include/ngraph/frontend/onnx_import/op/flatten.hpp
/usr/include/ngraph/frontend/onnx_import/op/floor.hpp
/usr/include/ngraph/frontend/onnx_import/op/gather.hpp
/usr/include/ngraph/frontend/onnx_import/op/gemm.hpp
/usr/include/ngraph/frontend/onnx_import/op/global_average_pool.hpp
/usr/include/ngraph/frontend/onnx_import/op/global_max_pool.hpp
/usr/include/ngraph/frontend/onnx_import/op/greater.hpp
/usr/include/ngraph/frontend/onnx_import/op/hard_sigmoid.hpp
/usr/include/ngraph/frontend/onnx_import/op/hardmax.hpp
/usr/include/ngraph/frontend/onnx_import/op/identity.hpp
/usr/include/ngraph/frontend/onnx_import/op/leaky_relu.hpp
/usr/include/ngraph/frontend/onnx_import/op/less.hpp
/usr/include/ngraph/frontend/onnx_import/op/log.hpp
/usr/include/ngraph/frontend/onnx_import/op/log_softmax.hpp
/usr/include/ngraph/frontend/onnx_import/op/lp_pool.hpp
/usr/include/ngraph/frontend/onnx_import/op/lrn.hpp
/usr/include/ngraph/frontend/onnx_import/op/lstm.hpp
/usr/include/ngraph/frontend/onnx_import/op/matmul.hpp
/usr/include/ngraph/frontend/onnx_import/op/matmul_integer.hpp
/usr/include/ngraph/frontend/onnx_import/op/max.hpp
/usr/include/ngraph/frontend/onnx_import/op/max_pool.hpp
/usr/include/ngraph/frontend/onnx_import/op/mean.hpp
/usr/include/ngraph/frontend/onnx_import/op/min.hpp
/usr/include/ngraph/frontend/onnx_import/op/mul.hpp
/usr/include/ngraph/frontend/onnx_import/op/neg.hpp
/usr/include/ngraph/frontend/onnx_import/op/not.hpp
/usr/include/ngraph/frontend/onnx_import/op/onehot.hpp
/usr/include/ngraph/frontend/onnx_import/op/or.hpp
/usr/include/ngraph/frontend/onnx_import/op/pad.hpp
/usr/include/ngraph/frontend/onnx_import/op/pow.hpp
/usr/include/ngraph/frontend/onnx_import/op/prelu.hpp
/usr/include/ngraph/frontend/onnx_import/op/qlinear_matmul.hpp
/usr/include/ngraph/frontend/onnx_import/op/quant_conv.hpp
/usr/include/ngraph/frontend/onnx_import/op/quantize_linear.hpp
/usr/include/ngraph/frontend/onnx_import/op/reciprocal.hpp
/usr/include/ngraph/frontend/onnx_import/op/reduce.hpp
/usr/include/ngraph/frontend/onnx_import/op/relu.hpp
/usr/include/ngraph/frontend/onnx_import/op/reshape.hpp
/usr/include/ngraph/frontend/onnx_import/op/selu.hpp
/usr/include/ngraph/frontend/onnx_import/op/shape.hpp
/usr/include/ngraph/frontend/onnx_import/op/shrink.hpp
/usr/include/ngraph/frontend/onnx_import/op/sigmoid.hpp
/usr/include/ngraph/frontend/onnx_import/op/sign.hpp
/usr/include/ngraph/frontend/onnx_import/op/sin.hpp
/usr/include/ngraph/frontend/onnx_import/op/sinh.hpp
/usr/include/ngraph/frontend/onnx_import/op/size.hpp
/usr/include/ngraph/frontend/onnx_import/op/slice.hpp
/usr/include/ngraph/frontend/onnx_import/op/softmax.hpp
/usr/include/ngraph/frontend/onnx_import/op/softplus.hpp
/usr/include/ngraph/frontend/onnx_import/op/softsign.hpp
/usr/include/ngraph/frontend/onnx_import/op/space_to_depth.hpp
/usr/include/ngraph/frontend/onnx_import/op/split.hpp
/usr/include/ngraph/frontend/onnx_import/op/sqrt.hpp
/usr/include/ngraph/frontend/onnx_import/op/squeeze.hpp
/usr/include/ngraph/frontend/onnx_import/op/sub.hpp
/usr/include/ngraph/frontend/onnx_import/op/sum.hpp
/usr/include/ngraph/frontend/onnx_import/op/tan.hpp
/usr/include/ngraph/frontend/onnx_import/op/tanh.hpp
/usr/include/ngraph/frontend/onnx_import/op/thresholded_relu.hpp
/usr/include/ngraph/frontend/onnx_import/op/topk.hpp
/usr/include/ngraph/frontend/onnx_import/op/transpose.hpp
/usr/include/ngraph/frontend/onnx_import/op/unsqueeze.hpp
/usr/include/ngraph/frontend/onnx_import/op/where.hpp
/usr/include/ngraph/frontend/onnx_import/op/xor.hpp
/usr/include/ngraph/frontend/onnx_import/ops_bridge.hpp
/usr/include/ngraph/frontend/onnx_import/utils/common.hpp
/usr/include/ngraph/frontend/onnx_import/utils/convpool.hpp
/usr/include/ngraph/frontend/onnx_import/utils/matmul_factory.hpp
/usr/include/ngraph/frontend/onnx_import/utils/reduction.hpp
/usr/include/ngraph/frontend/onnx_import/utils/reshape.hpp
/usr/include/ngraph/frontend/onnx_import/utils/rnn/activation_functions.hpp
/usr/include/ngraph/frontend/onnx_import/utils/variadic.hpp
/usr/include/ngraph/frontend/onnxifi/backend.hpp
/usr/include/ngraph/frontend/onnxifi/backend_manager.hpp
/usr/include/ngraph/frontend/onnxifi/exceptions.hpp
/usr/include/ngraph/frontend/onnxifi/executable.hpp
/usr/include/ngraph/frontend/onnxifi/span.hpp
/usr/include/ngraph/frontend/onnxifi/tensor.hpp
/usr/include/ngraph/function.hpp
/usr/include/ngraph/graph_util.hpp
/usr/include/ngraph/log.hpp
/usr/include/ngraph/ngraph.hpp
/usr/include/ngraph/ngraph_visibility.hpp
/usr/include/ngraph/node.hpp
/usr/include/ngraph/op/abs.hpp
/usr/include/ngraph/op/acos.hpp
/usr/include/ngraph/op/add.hpp
/usr/include/ngraph/op/all.hpp
/usr/include/ngraph/op/allreduce.hpp
/usr/include/ngraph/op/and.hpp
/usr/include/ngraph/op/any.hpp
/usr/include/ngraph/op/argmax.hpp
/usr/include/ngraph/op/argmin.hpp
/usr/include/ngraph/op/asin.hpp
/usr/include/ngraph/op/atan.hpp
/usr/include/ngraph/op/avg_pool.hpp
/usr/include/ngraph/op/batch_norm.hpp
/usr/include/ngraph/op/broadcast.hpp
/usr/include/ngraph/op/broadcast_distributed.hpp
/usr/include/ngraph/op/ceiling.hpp
/usr/include/ngraph/op/concat.hpp
/usr/include/ngraph/op/constant.hpp
/usr/include/ngraph/op/convert.hpp
/usr/include/ngraph/op/convolution.hpp
/usr/include/ngraph/op/cos.hpp
/usr/include/ngraph/op/cosh.hpp
/usr/include/ngraph/op/dequantize.hpp
/usr/include/ngraph/op/divide.hpp
/usr/include/ngraph/op/dot.hpp
/usr/include/ngraph/op/embedding_lookup.hpp
/usr/include/ngraph/op/equal.hpp
/usr/include/ngraph/op/erf.hpp
/usr/include/ngraph/op/exp.hpp
/usr/include/ngraph/op/experimental/batch_mat_mul.hpp
/usr/include/ngraph/op/experimental/dyn_broadcast.hpp
/usr/include/ngraph/op/experimental/dyn_pad.hpp
/usr/include/ngraph/op/experimental/dyn_reshape.hpp
/usr/include/ngraph/op/experimental/dyn_slice.hpp
/usr/include/ngraph/op/experimental/generate_mask.hpp
/usr/include/ngraph/op/experimental/layers/ctc_greedy_decoder.hpp
/usr/include/ngraph/op/experimental/layers/detection_output.hpp
/usr/include/ngraph/op/experimental/layers/interpolate.hpp
/usr/include/ngraph/op/experimental/layers/prior_box.hpp
/usr/include/ngraph/op/experimental/layers/prior_box_clustered.hpp
/usr/include/ngraph/op/experimental/layers/proposal.hpp
/usr/include/ngraph/op/experimental/layers/psroi_pooling.hpp
/usr/include/ngraph/op/experimental/layers/region_yolo.hpp
/usr/include/ngraph/op/experimental/layers/reorg_yolo.hpp
/usr/include/ngraph/op/experimental/layers/roi_pooling.hpp
/usr/include/ngraph/op/experimental/quantized_avg_pool.hpp
/usr/include/ngraph/op/experimental/quantized_concat.hpp
/usr/include/ngraph/op/experimental/quantized_conv.hpp
/usr/include/ngraph/op/experimental/quantized_conv_bias.hpp
/usr/include/ngraph/op/experimental/quantized_conv_relu.hpp
/usr/include/ngraph/op/experimental/quantized_dot.hpp
/usr/include/ngraph/op/experimental/quantized_dot_bias.hpp
/usr/include/ngraph/op/experimental/quantized_max_pool.hpp
/usr/include/ngraph/op/experimental/shape_of.hpp
/usr/include/ngraph/op/experimental/tile.hpp
/usr/include/ngraph/op/experimental/transpose.hpp
/usr/include/ngraph/op/floor.hpp
/usr/include/ngraph/op/fused/clamp.hpp
/usr/include/ngraph/op/fused/conv_fused.hpp
/usr/include/ngraph/op/fused/depth_to_space.hpp
/usr/include/ngraph/op/fused/elu.hpp
/usr/include/ngraph/op/fused/fake_quantize.hpp
/usr/include/ngraph/op/fused/gemm.hpp
/usr/include/ngraph/op/fused/grn.hpp
/usr/include/ngraph/op/fused/group_conv.hpp
/usr/include/ngraph/op/fused/hard_sigmoid.hpp
/usr/include/ngraph/op/fused/leaky_relu.hpp
/usr/include/ngraph/op/fused/mvn.hpp
/usr/include/ngraph/op/fused/normalize.hpp
/usr/include/ngraph/op/fused/prelu.hpp
/usr/include/ngraph/op/fused/scale_shift.hpp
/usr/include/ngraph/op/fused/shuffle_channels.hpp
/usr/include/ngraph/op/fused/space_to_depth.hpp
/usr/include/ngraph/op/fused/split.hpp
/usr/include/ngraph/op/fused/squared_difference.hpp
/usr/include/ngraph/op/fused/squeeze.hpp
/usr/include/ngraph/op/fused/unsqueeze.hpp
/usr/include/ngraph/op/fused_op_tbl.hpp
/usr/include/ngraph/op/gather.hpp
/usr/include/ngraph/op/gather_nd.hpp
/usr/include/ngraph/op/get_output_element.hpp
/usr/include/ngraph/op/greater.hpp
/usr/include/ngraph/op/greater_eq.hpp
/usr/include/ngraph/op/less.hpp
/usr/include/ngraph/op/less_eq.hpp
/usr/include/ngraph/op/log.hpp
/usr/include/ngraph/op/lrn.hpp
/usr/include/ngraph/op/max.hpp
/usr/include/ngraph/op/max_pool.hpp
/usr/include/ngraph/op/maximum.hpp
/usr/include/ngraph/op/min.hpp
/usr/include/ngraph/op/minimum.hpp
/usr/include/ngraph/op/multiply.hpp
/usr/include/ngraph/op/negative.hpp
/usr/include/ngraph/op/not.hpp
/usr/include/ngraph/op/not_equal.hpp
/usr/include/ngraph/op/one_hot.hpp
/usr/include/ngraph/op/op.hpp
/usr/include/ngraph/op/op_tbl.hpp
/usr/include/ngraph/op/or.hpp
/usr/include/ngraph/op/pad.hpp
/usr/include/ngraph/op/parameter.hpp
/usr/include/ngraph/op/passthrough.hpp
/usr/include/ngraph/op/power.hpp
/usr/include/ngraph/op/product.hpp
/usr/include/ngraph/op/quantize.hpp
/usr/include/ngraph/op/relu.hpp
/usr/include/ngraph/op/replace_slice.hpp
/usr/include/ngraph/op/reshape.hpp
/usr/include/ngraph/op/result.hpp
/usr/include/ngraph/op/reverse.hpp
/usr/include/ngraph/op/reverse_sequence.hpp
/usr/include/ngraph/op/scatter_add.hpp
/usr/include/ngraph/op/scatter_nd_add.hpp
/usr/include/ngraph/op/select.hpp
/usr/include/ngraph/op/sigmoid.hpp
/usr/include/ngraph/op/sign.hpp
/usr/include/ngraph/op/sin.hpp
/usr/include/ngraph/op/sinh.hpp
/usr/include/ngraph/op/slice.hpp
/usr/include/ngraph/op/softmax.hpp
/usr/include/ngraph/op/sqrt.hpp
/usr/include/ngraph/op/stop_gradient.hpp
/usr/include/ngraph/op/subtract.hpp
/usr/include/ngraph/op/sum.hpp
/usr/include/ngraph/op/tan.hpp
/usr/include/ngraph/op/tanh.hpp
/usr/include/ngraph/op/topk.hpp
/usr/include/ngraph/op/util/arithmetic_reduction.hpp
/usr/include/ngraph/op/util/attr_types.hpp
/usr/include/ngraph/op/util/binary_elementwise_arithmetic.hpp
/usr/include/ngraph/op/util/binary_elementwise_comparison.hpp
/usr/include/ngraph/op/util/binary_elementwise_logical.hpp
/usr/include/ngraph/op/util/broadcasting.hpp
/usr/include/ngraph/op/util/fused_op.hpp
/usr/include/ngraph/op/util/index_reduction.hpp
/usr/include/ngraph/op/util/logical_reduction.hpp
/usr/include/ngraph/op/util/op_annotations.hpp
/usr/include/ngraph/op/util/reshape.hpp
/usr/include/ngraph/op/util/unary_elementwise_arithmetic.hpp
/usr/include/ngraph/partial_shape.hpp
/usr/include/ngraph/pass/algebraic_simplification.hpp
/usr/include/ngraph/pass/assign_layout.hpp
/usr/include/ngraph/pass/batch_fusion.hpp
/usr/include/ngraph/pass/common_function_collection.hpp
/usr/include/ngraph/pass/concat_fusion.hpp
/usr/include/ngraph/pass/constant_folding.hpp
/usr/include/ngraph/pass/constant_to_broadcast.hpp
/usr/include/ngraph/pass/core_fusion.hpp
/usr/include/ngraph/pass/cse.hpp
/usr/include/ngraph/pass/dump_sorted.hpp
/usr/include/ngraph/pass/dyn_elimination.hpp
/usr/include/ngraph/pass/fused_op_decomposition.hpp
/usr/include/ngraph/pass/get_output_element_elimination.hpp
/usr/include/ngraph/pass/graph_rewrite.hpp
/usr/include/ngraph/pass/implicit_broadcast_elimination.hpp
/usr/include/ngraph/pass/like_replacement.hpp
/usr/include/ngraph/pass/liveness.hpp
/usr/include/ngraph/pass/manager.hpp
/usr/include/ngraph/pass/manager_state.hpp
/usr/include/ngraph/pass/memory_layout.hpp
/usr/include/ngraph/pass/memory_visualize.hpp
/usr/include/ngraph/pass/nop_elimination.hpp
/usr/include/ngraph/pass/pass.hpp
/usr/include/ngraph/pass/pass_config.hpp
/usr/include/ngraph/pass/pass_util.hpp
/usr/include/ngraph/pass/prefix_reshape_elimination.hpp
/usr/include/ngraph/pass/propagate_cacheability.hpp
/usr/include/ngraph/pass/reshape_elimination.hpp
/usr/include/ngraph/pass/reshape_sinking.hpp
/usr/include/ngraph/pass/serialize.hpp
/usr/include/ngraph/pass/shape_relevance.hpp
/usr/include/ngraph/pass/validate_graph.hpp
/usr/include/ngraph/pass/visualize_tree.hpp
/usr/include/ngraph/pass/zero_dim_tensor_elimination.hpp
/usr/include/ngraph/pattern/matcher.hpp
/usr/include/ngraph/pattern/op/any.hpp
/usr/include/ngraph/pattern/op/any_of.hpp
/usr/include/ngraph/pattern/op/label.hpp
/usr/include/ngraph/pattern/op/pattern.hpp
/usr/include/ngraph/pattern/op/skip.hpp
/usr/include/ngraph/placement.hpp
/usr/include/ngraph/provenance.hpp
/usr/include/ngraph/rank.hpp
/usr/include/ngraph/runtime/aligned_buffer.hpp
/usr/include/ngraph/runtime/backend.hpp
/usr/include/ngraph/runtime/backend_manager.hpp
/usr/include/ngraph/runtime/cpu/builder/halide_generators.hpp
/usr/include/ngraph/runtime/cpu/builder/reduction.hpp
/usr/include/ngraph/runtime/cpu/cpu_backend.hpp
/usr/include/ngraph/runtime/cpu/cpu_backend_visibility.h
/usr/include/ngraph/runtime/cpu/cpu_builder.hpp
/usr/include/ngraph/runtime/cpu/cpu_call_frame.hpp
/usr/include/ngraph/runtime/cpu/cpu_cse.hpp
/usr/include/ngraph/runtime/cpu/cpu_debugger.hpp
/usr/include/ngraph/runtime/cpu/cpu_eigen_utils.hpp
/usr/include/ngraph/runtime/cpu/cpu_emitter.hpp
/usr/include/ngraph/runtime/cpu/cpu_executor.hpp
/usr/include/ngraph/runtime/cpu/cpu_external_function.hpp
/usr/include/ngraph/runtime/cpu/cpu_kernel_emitters.hpp
/usr/include/ngraph/runtime/cpu/cpu_kernel_utils.hpp
/usr/include/ngraph/runtime/cpu/cpu_kernels.hpp
/usr/include/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
/usr/include/ngraph/runtime/cpu/cpu_op_annotations.hpp
/usr/include/ngraph/runtime/cpu/cpu_runtime_context.hpp
/usr/include/ngraph/runtime/cpu/cpu_tensor_view.hpp
/usr/include/ngraph/runtime/cpu/cpu_tensor_view_wrapper.hpp
/usr/include/ngraph/runtime/cpu/cpu_tracing.hpp
/usr/include/ngraph/runtime/cpu/cpu_visualize_tree.hpp
/usr/include/ngraph/runtime/cpu/kernel/abs.hpp
/usr/include/ngraph/runtime/cpu/kernel/acos.hpp
/usr/include/ngraph/runtime/cpu/kernel/add.hpp
/usr/include/ngraph/runtime/cpu/kernel/and.hpp
/usr/include/ngraph/runtime/cpu/kernel/argmax.hpp
/usr/include/ngraph/runtime/cpu/kernel/argmin.hpp
/usr/include/ngraph/runtime/cpu/kernel/asin.hpp
/usr/include/ngraph/runtime/cpu/kernel/atan.hpp
/usr/include/ngraph/runtime/cpu/kernel/avg_pool.hpp
/usr/include/ngraph/runtime/cpu/kernel/batchnorm.hpp
/usr/include/ngraph/runtime/cpu/kernel/broadcast.hpp
/usr/include/ngraph/runtime/cpu/kernel/ceil.hpp
/usr/include/ngraph/runtime/cpu/kernel/concat.hpp
/usr/include/ngraph/runtime/cpu/kernel/convert.hpp
/usr/include/ngraph/runtime/cpu/kernel/convolution.hpp
/usr/include/ngraph/runtime/cpu/kernel/cos.hpp
/usr/include/ngraph/runtime/cpu/kernel/cosh.hpp
/usr/include/ngraph/runtime/cpu/kernel/cwise_pow.hpp
/usr/include/ngraph/runtime/cpu/kernel/divide.hpp
/usr/include/ngraph/runtime/cpu/kernel/dot.hpp
/usr/include/ngraph/runtime/cpu/kernel/dropout.hpp
/usr/include/ngraph/runtime/cpu/kernel/equal.hpp
/usr/include/ngraph/runtime/cpu/kernel/erf.hpp
/usr/include/ngraph/runtime/cpu/kernel/exp.hpp
/usr/include/ngraph/runtime/cpu/kernel/floor.hpp
/usr/include/ngraph/runtime/cpu/kernel/gather.hpp
/usr/include/ngraph/runtime/cpu/kernel/greater.hpp
/usr/include/ngraph/runtime/cpu/kernel/greater_eq.hpp
/usr/include/ngraph/runtime/cpu/kernel/less.hpp
/usr/include/ngraph/runtime/cpu/kernel/less_eq.hpp
/usr/include/ngraph/runtime/cpu/kernel/log.hpp
/usr/include/ngraph/runtime/cpu/kernel/max_pool.hpp
/usr/include/ngraph/runtime/cpu/kernel/maximum.hpp
/usr/include/ngraph/runtime/cpu/kernel/minimum.hpp
/usr/include/ngraph/runtime/cpu/kernel/multiply.hpp
/usr/include/ngraph/runtime/cpu/kernel/negative.hpp
/usr/include/ngraph/runtime/cpu/kernel/not.hpp
/usr/include/ngraph/runtime/cpu/kernel/not_equal.hpp
/usr/include/ngraph/runtime/cpu/kernel/one_hot.hpp
/usr/include/ngraph/runtime/cpu/kernel/or.hpp
/usr/include/ngraph/runtime/cpu/kernel/pad.hpp
/usr/include/ngraph/runtime/cpu/kernel/reduce_max.hpp
/usr/include/ngraph/runtime/cpu/kernel/reduce_min.hpp
/usr/include/ngraph/runtime/cpu/kernel/reduce_product.hpp
/usr/include/ngraph/runtime/cpu/kernel/reduce_sum.hpp
/usr/include/ngraph/runtime/cpu/kernel/relu.hpp
/usr/include/ngraph/runtime/cpu/kernel/replace_slice.hpp
/usr/include/ngraph/runtime/cpu/kernel/reshape.hpp
/usr/include/ngraph/runtime/cpu/kernel/result.hpp
/usr/include/ngraph/runtime/cpu/kernel/reverse.hpp
/usr/include/ngraph/runtime/cpu/kernel/reverse_sequence.hpp
/usr/include/ngraph/runtime/cpu/kernel/scatter_add.hpp
/usr/include/ngraph/runtime/cpu/kernel/select.hpp
/usr/include/ngraph/runtime/cpu/kernel/sigmoid_multiply.hpp
/usr/include/ngraph/runtime/cpu/kernel/sign.hpp
/usr/include/ngraph/runtime/cpu/kernel/sin.hpp
/usr/include/ngraph/runtime/cpu/kernel/sinh.hpp
/usr/include/ngraph/runtime/cpu/kernel/slice.hpp
/usr/include/ngraph/runtime/cpu/kernel/softmax.hpp
/usr/include/ngraph/runtime/cpu/kernel/sqrt.hpp
/usr/include/ngraph/runtime/cpu/kernel/subtract.hpp
/usr/include/ngraph/runtime/cpu/kernel/tan.hpp
/usr/include/ngraph/runtime/cpu/kernel/tanh.hpp
/usr/include/ngraph/runtime/cpu/kernel/tile.hpp
/usr/include/ngraph/runtime/cpu/kernel/update_slice.hpp
/usr/include/ngraph/runtime/cpu/mkldnn_emitter.hpp
/usr/include/ngraph/runtime/cpu/mkldnn_invoke.hpp
/usr/include/ngraph/runtime/cpu/mkldnn_utils.hpp
/usr/include/ngraph/runtime/cpu/op/batch_mat_mul_transpose.hpp
/usr/include/ngraph/runtime/cpu/op/batch_norm_relu.hpp
/usr/include/ngraph/runtime/cpu/op/bounded_relu.hpp
/usr/include/ngraph/runtime/cpu/op/conv_add.hpp
/usr/include/ngraph/runtime/cpu/op/conv_relu.hpp
/usr/include/ngraph/runtime/cpu/op/convert_layout.hpp
/usr/include/ngraph/runtime/cpu/op/deconv.hpp
/usr/include/ngraph/runtime/cpu/op/dropout.hpp
/usr/include/ngraph/runtime/cpu/op/group_conv_bias.hpp
/usr/include/ngraph/runtime/cpu/op/halide_op.hpp
/usr/include/ngraph/runtime/cpu/op/leaky_relu.hpp
/usr/include/ngraph/runtime/cpu/op/loop_kernel.hpp
/usr/include/ngraph/runtime/cpu/op/lstm.hpp
/usr/include/ngraph/runtime/cpu/op/matmul_bias.hpp
/usr/include/ngraph/runtime/cpu/op/max_pool_with_indices.hpp
/usr/include/ngraph/runtime/cpu/op/quantized_matmul.hpp
/usr/include/ngraph/runtime/cpu/op/rnn.hpp
/usr/include/ngraph/runtime/cpu/op/rnn_utils.hpp
/usr/include/ngraph/runtime/cpu/op/sigmoid.hpp
/usr/include/ngraph/runtime/cpu/op/sigmoid_mul.hpp
/usr/include/ngraph/runtime/cpu/op/update_slice.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_assignment.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_collapse_dims.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_fusion.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_layout.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_loop_kernel_fusion.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_mat_fusion.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_memory_assignment.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_memory_optimization.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_rnn_fusion.hpp
/usr/include/ngraph/runtime/cpu/pass/cpu_workspace_insertion.hpp
/usr/include/ngraph/runtime/cpu/pass/halide_subgraph_extraction.hpp
/usr/include/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
/usr/include/ngraph/runtime/dynamic/dynamic_backend.hpp
/usr/include/ngraph/runtime/executable.hpp
/usr/include/ngraph/runtime/generic_cpu/gcpu_backend.hpp
/usr/include/ngraph/runtime/generic_cpu/gcpu_executable.hpp
/usr/include/ngraph/runtime/generic_cpu/kernel/broadcast.hpp
/usr/include/ngraph/runtime/generic_cpu/kernel/dot.hpp
/usr/include/ngraph/runtime/generic_cpu/kernel/reshape.hpp
/usr/include/ngraph/runtime/generic_cpu/kernel/result.hpp
/usr/include/ngraph/runtime/generic_cpu/node_wrapper.hpp
/usr/include/ngraph/runtime/gpu/cublas_emitter.hpp
/usr/include/ngraph/runtime/gpu/cuda_emitter.hpp
/usr/include/ngraph/runtime/gpu/cuda_error_check.hpp
/usr/include/ngraph/runtime/gpu/cudnn_descriptors.hpp
/usr/include/ngraph/runtime/gpu/cudnn_emitter.hpp
/usr/include/ngraph/runtime/gpu/cudnn_host_parameters.hpp
/usr/include/ngraph/runtime/gpu/cudnn_invoke.hpp
/usr/include/ngraph/runtime/gpu/gpu_backend.hpp
/usr/include/ngraph/runtime/gpu/gpu_call_frame.hpp
/usr/include/ngraph/runtime/gpu/gpu_compiled_function.hpp
/usr/include/ngraph/runtime/gpu/gpu_cuda_context_manager.hpp
/usr/include/ngraph/runtime/gpu/gpu_cuda_function_builder.hpp
/usr/include/ngraph/runtime/gpu/gpu_cuda_function_pool.hpp
/usr/include/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
/usr/include/ngraph/runtime/gpu/gpu_cuda_kernel_ops.hpp
/usr/include/ngraph/runtime/gpu/gpu_emitter.hpp
/usr/include/ngraph/runtime/gpu/gpu_external_function.hpp
/usr/include/ngraph/runtime/gpu/gpu_host_parameters.hpp
/usr/include/ngraph/runtime/gpu/gpu_internal_function.hpp
/usr/include/ngraph/runtime/gpu/gpu_invoke.hpp
/usr/include/ngraph/runtime/gpu/gpu_kernel_args.hpp
/usr/include/ngraph/runtime/gpu/gpu_kernel_emitters.hpp
/usr/include/ngraph/runtime/gpu/gpu_memory_manager.hpp
/usr/include/ngraph/runtime/gpu/gpu_op_annotations.hpp
/usr/include/ngraph/runtime/gpu/gpu_primitive_emitter.hpp
/usr/include/ngraph/runtime/gpu/gpu_runtime_constructor.hpp
/usr/include/ngraph/runtime/gpu/gpu_runtime_context.hpp
/usr/include/ngraph/runtime/gpu/gpu_tensor.hpp
/usr/include/ngraph/runtime/gpu/gpu_tensor_wrapper.hpp
/usr/include/ngraph/runtime/gpu/gpu_util.hpp
/usr/include/ngraph/runtime/gpu/host_emitter.hpp
/usr/include/ngraph/runtime/gpu/nvcc/kernels.hpp
/usr/include/ngraph/runtime/gpu/nvdiff.hpp
/usr/include/ngraph/runtime/gpu/nvrtc/helpers.hpp
/usr/include/ngraph/runtime/gpu/nvshape.hpp
/usr/include/ngraph/runtime/gpu/op/batch_norm.hpp
/usr/include/ngraph/runtime/gpu/op/op_tbl.hpp
/usr/include/ngraph/runtime/gpu/op/rnn.hpp
/usr/include/ngraph/runtime/gpu/pass/gpu_batch_norm_cache.hpp
/usr/include/ngraph/runtime/gpu/pass/gpu_layout.hpp
/usr/include/ngraph/runtime/gpu/pass/gpu_rnn_fusion.hpp
/usr/include/ngraph/runtime/gpu/pass/tensor_memory_reservation.hpp
/usr/include/ngraph/runtime/gpu/type_info.hpp
/usr/include/ngraph/runtime/gpuh/gpuh_backend.hpp
/usr/include/ngraph/runtime/host_tensor.hpp
/usr/include/ngraph/runtime/intelgpu/intelgpu_backend.hpp
/usr/include/ngraph/runtime/intelgpu/intelgpu_executable.hpp
/usr/include/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
/usr/include/ngraph/runtime/intelgpu/intelgpu_layout.hpp
/usr/include/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
/usr/include/ngraph/runtime/intelgpu/intelgpu_tensor_view.hpp
/usr/include/ngraph/runtime/intelgpu/visualize_tree.hpp
/usr/include/ngraph/runtime/interpreter/int_backend.hpp
/usr/include/ngraph/runtime/interpreter/int_executable.hpp
/usr/include/ngraph/runtime/interpreter/int_visibility.hpp
/usr/include/ngraph/runtime/interpreter/node_wrapper.hpp
/usr/include/ngraph/runtime/nop/nop_backend.hpp
/usr/include/ngraph/runtime/performance_counter.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_backend.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_build.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_builder.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_compilation_cache.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_compiler.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_config.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_convpool_formatter.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_executable.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_impl.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_logger.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_ops_convolution.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_ops_implicit_broadcast.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_ops_replicate.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_ops_winograd.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_concat_elision.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_concat_split.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_replicate_combination.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_pass_winograd.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_tensor.hpp
/usr/include/ngraph/runtime/plaidml/plaidml_translate.hpp
/usr/include/ngraph/runtime/reference/abs.hpp
/usr/include/ngraph/runtime/reference/acos.hpp
/usr/include/ngraph/runtime/reference/add.hpp
/usr/include/ngraph/runtime/reference/all.hpp
/usr/include/ngraph/runtime/reference/allreduce.hpp
/usr/include/ngraph/runtime/reference/and.hpp
/usr/include/ngraph/runtime/reference/any.hpp
/usr/include/ngraph/runtime/reference/argmax.hpp
/usr/include/ngraph/runtime/reference/argmin.hpp
/usr/include/ngraph/runtime/reference/asin.hpp
/usr/include/ngraph/runtime/reference/atan.hpp
/usr/include/ngraph/runtime/reference/avg_pool.hpp
/usr/include/ngraph/runtime/reference/batch_mat_mul.hpp
/usr/include/ngraph/runtime/reference/batch_norm.hpp
/usr/include/ngraph/runtime/reference/broadcast.hpp
/usr/include/ngraph/runtime/reference/broadcast_distributed.hpp
/usr/include/ngraph/runtime/reference/ceiling.hpp
/usr/include/ngraph/runtime/reference/concat.hpp
/usr/include/ngraph/runtime/reference/constant.hpp
/usr/include/ngraph/runtime/reference/convert.hpp
/usr/include/ngraph/runtime/reference/convolution.hpp
/usr/include/ngraph/runtime/reference/copy.hpp
/usr/include/ngraph/runtime/reference/cos.hpp
/usr/include/ngraph/runtime/reference/cosh.hpp
/usr/include/ngraph/runtime/reference/dequantize.hpp
/usr/include/ngraph/runtime/reference/divide.hpp
/usr/include/ngraph/runtime/reference/dot.hpp
/usr/include/ngraph/runtime/reference/embedding_lookup.hpp
/usr/include/ngraph/runtime/reference/equal.hpp
/usr/include/ngraph/runtime/reference/erf.hpp
/usr/include/ngraph/runtime/reference/exp.hpp
/usr/include/ngraph/runtime/reference/floor.hpp
/usr/include/ngraph/runtime/reference/gather.hpp
/usr/include/ngraph/runtime/reference/gather_nd.hpp
/usr/include/ngraph/runtime/reference/generate_mask.hpp
/usr/include/ngraph/runtime/reference/greater.hpp
/usr/include/ngraph/runtime/reference/greater_eq.hpp
/usr/include/ngraph/runtime/reference/less.hpp
/usr/include/ngraph/runtime/reference/less_eq.hpp
/usr/include/ngraph/runtime/reference/log.hpp
/usr/include/ngraph/runtime/reference/lrn.hpp
/usr/include/ngraph/runtime/reference/max.hpp
/usr/include/ngraph/runtime/reference/max_pool.hpp
/usr/include/ngraph/runtime/reference/maximum.hpp
/usr/include/ngraph/runtime/reference/min.hpp
/usr/include/ngraph/runtime/reference/minimum.hpp
/usr/include/ngraph/runtime/reference/multiply.hpp
/usr/include/ngraph/runtime/reference/negate.hpp
/usr/include/ngraph/runtime/reference/not.hpp
/usr/include/ngraph/runtime/reference/not_equal.hpp
/usr/include/ngraph/runtime/reference/one_hot.hpp
/usr/include/ngraph/runtime/reference/or.hpp
/usr/include/ngraph/runtime/reference/pad.hpp
/usr/include/ngraph/runtime/reference/power.hpp
/usr/include/ngraph/runtime/reference/product.hpp
/usr/include/ngraph/runtime/reference/quantize.hpp
/usr/include/ngraph/runtime/reference/relu.hpp
/usr/include/ngraph/runtime/reference/replace_slice.hpp
/usr/include/ngraph/runtime/reference/reshape.hpp
/usr/include/ngraph/runtime/reference/result.hpp
/usr/include/ngraph/runtime/reference/reverse.hpp
/usr/include/ngraph/runtime/reference/reverse_sequence.hpp
/usr/include/ngraph/runtime/reference/scatter_add.hpp
/usr/include/ngraph/runtime/reference/scatter_nd_add.hpp
/usr/include/ngraph/runtime/reference/select.hpp
/usr/include/ngraph/runtime/reference/shape_of.hpp
/usr/include/ngraph/runtime/reference/sigmoid.hpp
/usr/include/ngraph/runtime/reference/sign.hpp
/usr/include/ngraph/runtime/reference/sin.hpp
/usr/include/ngraph/runtime/reference/sinh.hpp
/usr/include/ngraph/runtime/reference/slice.hpp
/usr/include/ngraph/runtime/reference/softmax.hpp
/usr/include/ngraph/runtime/reference/sqrt.hpp
/usr/include/ngraph/runtime/reference/subtract.hpp
/usr/include/ngraph/runtime/reference/sum.hpp
/usr/include/ngraph/runtime/reference/tan.hpp
/usr/include/ngraph/runtime/reference/tanh.hpp
/usr/include/ngraph/runtime/reference/topk.hpp
/usr/include/ngraph/runtime/tensor.hpp
/usr/include/ngraph/serializer.hpp
/usr/include/ngraph/shape.hpp
/usr/include/ngraph/shape_util.hpp
/usr/include/ngraph/specialize_function.hpp
/usr/include/ngraph/state/rng_state.hpp
/usr/include/ngraph/state/state.hpp
/usr/include/ngraph/strides.hpp
/usr/include/ngraph/type/bfloat16.hpp
/usr/include/ngraph/type/element_type.hpp
/usr/include/ngraph/type/float16.hpp
/usr/include/ngraph/util.hpp
/usr/include/ngraph/validation_util.hpp
/usr/include/ngraph/version.hpp
/usr/include/ngraph/version.in.hpp
/usr/lib64/haswell/avx512_1/libngraph.so
/usr/lib64/haswell/libngraph.so
/usr/lib64/libngraph.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/avx512_1/libngraph.so.0.22
/usr/lib64/haswell/libngraph.so.0.22
/usr/lib64/libngraph.so.0.22

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ngraph/02d5a8aa5c17fd84b6d53f0ce2820f7df439873c
/usr/share/package-licenses/ngraph/051b823186e06740361b3bd1ec3e1ba37b836f36
/usr/share/package-licenses/ngraph/293bda57df5fd753d536918973e0cbdc7ad2a3f5
/usr/share/package-licenses/ngraph/37571ac0358829b2175835de61c68818dd709239
/usr/share/package-licenses/ngraph/385bdbc74ad1af072775c2366445b9a20b96f1d0
/usr/share/package-licenses/ngraph/3fa2daf91c6f9dcf7c767a7b755fa36a23debc4f
/usr/share/package-licenses/ngraph/48a395f1045c617d1b407e8372bd77c8f71bf86c
/usr/share/package-licenses/ngraph/594e887872eacc74920a5eb310c1f9ee34dcf131
/usr/share/package-licenses/ngraph/60e7040879300ea5e3cb2f6e4437b001ef85811b
/usr/share/package-licenses/ngraph/62e83dae35534c2dd6abbefe96698b182a900c15
/usr/share/package-licenses/ngraph/7a511ea6464485d919713d82ca7a175e3be9b407
/usr/share/package-licenses/ngraph/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/ngraph/840cef56b46b261f9d3faba6e79f4da93126f63a
/usr/share/package-licenses/ngraph/8d9c29c48565d4d4283216c4c63e4fe31cc56257
/usr/share/package-licenses/ngraph/9e66a6e615665d81e0518564c4f93927a41a5d8c
/usr/share/package-licenses/ngraph/b63a31e4a6af5b8d9432771d7e737b8cbd40315b
/usr/share/package-licenses/ngraph/f37bc6749b691bf29592797db379cf0e390bb8b7
/usr/share/package-licenses/ngraph/ff83fbccde4452fe6eded294096f1f164c3519dd
